# Generated by Django 4.0.6 on 2022-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender1', models.EmailField(max_length=254)),
                ('sender2', models.EmailField(max_length=254)),
                ('sender3', models.EmailField(max_length=254)),
                ('sender4', models.EmailField(max_length=254)),
                ('cc1', models.EmailField(max_length=254)),
                ('cc2', models.EmailField(max_length=254)),
                ('cc3', models.EmailField(max_length=254)),
                ('cc4', models.EmailField(max_length=254)),
                ('hour', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('days', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('Engineer_Name', models.CharField(choices=[('rameez1.py', 'rameez2.py'), ('rameez2.py', 'rameez1.py')], max_length=100)),
            ],
        ),
    ]
