# Generated by Django 4.0.6 on 2022-11-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender1', models.EmailField(max_length=254)),
                ('sender2', models.EmailField(max_length=254)),
                ('sender3', models.EmailField(max_length=254)),
                ('sender4', models.EmailField(max_length=254)),
                ('cc1', models.EmailField(max_length=254)),
                ('cc2', models.EmailField(max_length=254)),
                ('cc3', models.EmailField(max_length=254)),
                ('cc4', models.EmailField(max_length=254)),
                ('hour', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('Engineer_Name', models.CharField(choices=[('1', 'tests.py'), ('2', 'models.py'), ('3', 'cron.py'), ('4', 'views.py'), ('5', 'forms.py')], max_length=100)),
            ],
        ),
    ]
