# Generated by Django 4.0.6 on 2022-11-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Engineer_Name',
            field=models.CharField(choices=[('1', '__init__.py'), ('2', '0001_initial.py'), ('3', 'tests.py'), ('4', 'models.py'), ('5', 'views.py'), ('6', '__init__.py'), ('7', 'cron.py'), ('8', 'forms.py'), ('9', 'admin.py'), ('10', 'apps.py'), ('11', 'urls.py')], max_length=100),
        ),
    ]
