# Generated by Django 4.0.6 on 2022-12-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_alter_student_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='days',
            field=models.BooleanField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')]),
        ),
    ]
