# Generated by Django 3.2.18 on 2023-04-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_auto_20230331_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Engineer_Name',
            field=models.CharField(choices=[('rameez2.py', '/home/ubuntu/reportproject/rameez/rameez2.py'), ('rameez1.py', '/home/ubuntu/reportproject/rameez/rameez1.py')], max_length=100),
        ),
    ]
