# Generated by Django 3.2.18 on 2023-04-07 04:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_alter_student_engineer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Engineer_Name',
            field=models.CharField(choices=[('script2', 'script2'), ('rameez1', 'rameez1'), ('script1', 'script1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56),
        ),
    ]
