# Generated by Django 3.2.18 on 2023-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0012_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Engineer_Name',
            field=models.CharField(choices=[('script2', 'script2'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=100),
        ),
    ]
